name: Streamlined Releases Action
description: |
  A GitHub Action to streamline releases by automating the process of updating version numbers
  and generating changelogs.
author: LooLzzz

inputs:
  myInput:
    description: Input to use
    default: world

outputs:
  myOutput:
    description: Output from the action

runs:
  using: docker
  image: Dockerfile
