name: Streamlined Releases Action
description: |
  A GitHub Action to streamline releases by automating the process of updating version numbers
  and generating changelogs.
author: LooLzzz

inputs:
  git_username:
    description: Git username for the bump commit actor
    required: false
    default: github-actions[bot]
  git_email:
    description: Git email for the bump commit actor
    required: false
    default: github-actions[bot]@users.noreply.github.com
  bump_commit_message:
    description: Template for the bump commit message. Use {version} as a placeholder for the bumped version.
    required: false
    default: "chore(release): Bumped version to {version}"
  changelog_filepath:
    description: Path to the changelog file.
    required: false
    default: CHANGELOG.md
  main_branch:
    description: Name of the main release branch.
    required: false
    default: main
  staging_branch:
    description: Name of the staging release branch.
    required: false
    default: stg
  dev_branch:
    description: Name of the dev release branch.
    required: false
    default: dev

outputs:
  diff_changelog:
    description: The diff changelog generated by the action
  changelog:
    description: The full changelog generated by the action

runs:
  using: docker
  # image: Dockerfile
  image: docker://ghcr.io/loolzzz/streamlined-releases:latest
