version: 1
disable_existing_loggers: False


formatters:
  default:
    "()": logging.Formatter
    datefmt: "%Y-%m-%d %H:%M:%S"
    # format: "[%(levelname)s] %(name)s - %(message)s"
    format: "[%(levelname)s] %(filename)s - %(message)s"
    # format: "[%(levelname)s] %(filename)s:%(lineno)d - %(message)s"

handlers:
  default:
    formatter: default
    class: logging.StreamHandler

root:
  level: INFO
  handlers: [default]
  propagate: no
